import type { PricingPlan } from '~/types'

export const PRICING_PLANS: PricingPlan[] = [
  {
    name: 'Free',
    price: 0,
    period: 'month',
    eventsLimit: '5k',
    retention: '14 days',
    projects: 1,
    features: [
      '5k events/month',
      '14 days retention',
      '1 project',
      'Email support',
      'API access',
    ],
  },
  {
    name: 'Starter',
    price: 19,
    period: 'month',
    eventsLimit: '100k',
    retention: '90 days',
    projects: 5,
    popular: true,
    features: [
      '100k events/month',
      '90 days retention',
      '5 projects',
      'Email support',
      'API access',
      'CSV export',
    ],
  },
  {
    name: 'Pro',
    price: 49,
    period: 'month',
    eventsLimit: '500k',
    retention: '1 year',
    projects: 20,
    features: [
      '500k events/month',
      '1 year retention',
      '20 projects',
      'Priority support',
      'API access',
      'CSV export',
      'SOC 2 export',
    ],
  },
  {
    name: 'Business',
    price: 149,
    period: 'month',
    eventsLimit: '2M',
    retention: '3 years',
    projects: 100,
    features: [
      '2M events/month',
      '3 years retention',
      '100 projects',
      'Dedicated support',
      'API access',
      'CSV export',
      'SOC 2 export',
      'Webhooks',
    ],
  },
]
